# Reference: https://github.com/i3/i3/blob/next/etc/config


after-startup-command = [
# JankyBorders has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
    # 'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xffa6e3a1 inactive_color=0xffa6adc8 hidpi=true width=8.0'
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = false

[key-mapping.key-notation-to-key-code]
#hyper = 'u-a'
[mode.main.binding]
cmd-h = []

alt-h = 'focus left --boundaries-action wrap-around-the-workspace'
alt-j = 'focus down --boundaries-action wrap-around-the-workspace'
alt-k = 'focus up --boundaries-action wrap-around-the-workspace'
alt-l = 'focus right --boundaries-action wrap-around-the-workspace'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'

alt-f = 'fullscreen'

#alt-s = 'layout v_accordion' # 'layout stacking' in i3
#alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-q = 'layout accordion horizontal vertical'
alt-w = 'layout horizontal vertical'
alt-e = 'layout tiles accordion'
alt-d = 'layout floating tiling'

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
#alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
#alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[workspace-to-monitor-force-assignment]
1 = ['dell', 'built-in']
2 = ['dell', 'built-in']
3 = ['dell', 'built-in']
5 = ['dell', 'built-in']
4 = 'built-in'         
7 = 'built-in'
8 = ['dell', 'built-in']
9 = ['dell', 'built-in']
10 = ['dell', 'built-in']         

[mode.resize.binding]
h = 'resize width -100'
j = 'resize height +100'
k = 'resize height -100'
l = 'resize width +100'
enter = 'mode main'
esc = 'mode main'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 30
inner.vertical =   30
outer.left =       30
outer.bottom =     30
outer.top =        30
outer.right =      30


[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
if.window-title-regex-substring = 'Picture-in-Picture'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = "move-node-to-workspace 1"

# [[on-window-detected]]
# if.app-id = 'app.zen-browser.zen'
# if.window-title-regex-substring = 'Picture-in-Picture'
# run = "layout floating"
# check-further-callbacks = true
# [[on-window-detected]]
# if.during-aerospace-startup = false
# if.app-id = 'app.zen-browser.zen'
# if.window-title-regex-substring = 'Picture-in-Picture'
# # run = ['layout floating']
# run = 'layout floating'


# [[on-window-detected]]
# if.app-id = 'app.zen-browser.zen'
# if.window-title-regex-substring = 'Picture-in-Picture'
# run = ['layout floating']
#

# [[on-window-detected]]
# if.app-id = 'org.mozilla.firefoxdeveloperedition'
# if.window-title-regex-substring = 'Picture-in-Picture'
# run = ['layout floating']



[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace 4"
